<?php 
      $column_array =array (
  1 => 
  array (
    0 => '1',
    'id' => '1',
    1 => '0',
    'pid' => '0',
    2 => 'other',
    'model' => 'other',
    3 => '官网首页',
    'name' => '官网首页',
    4 => '',
    'catalog' => '',
    5 => 'index.html',
    'link' => 'index.html',
    6 => '',
    'target' => '',
    7 => '1',
    'porder' => '1',
    8 => 'index.htm',
    'template' => 'index.htm',
    9 => 'show',
    'display' => 'show',
  ),
  2 => 
  array (
    0 => '2',
    'id' => '2',
    1 => '0',
    'pid' => '0',
    2 => 'common',
    'model' => 'common',
    3 => '汤先生',
    'name' => '汤先生',
    4 => '',
    'catalog' => '',
    5 => 'about.html',
    'link' => 'about.html',
    6 => '',
    'target' => '',
    7 => '2',
    'porder' => '2',
    8 => 'about.htm',
    'template' => 'about.htm',
    9 => 'show',
    'display' => 'show',
  ),
  3 => 
  array (
    0 => '3',
    'id' => '3',
    1 => '0',
    'pid' => '0',
    2 => 'article',
    'model' => 'article',
    3 => '新闻动态',
    'name' => '新闻动态',
    4 => 'news',
    'catalog' => 'news',
    5 => 'news/page_1.html',
    'link' => 'news/page_1.html',
    6 => '',
    'target' => '',
    7 => '3',
    'porder' => '3',
    8 => 'news.htm',
    'template' => 'news.htm',
    9 => 'show',
    'display' => 'show',
    'child' => 
    array (
      7 => 
      array (
        0 => '7',
        'id' => '7',
        1 => '3',
        'pid' => '3',
        2 => 'other',
        'model' => 'other',
        3 => '新闻详情',
        'name' => '新闻详情',
        4 => 'news',
        'catalog' => 'news',
        5 => '',
        'link' => '',
        6 => '_blank',
        'target' => '_blank',
        7 => '1',
        'porder' => '1',
        8 => 'news_detail.htm',
        'template' => 'news_detail.htm',
        9 => 'hide',
        'display' => 'hide',
      ),
    ),
  ),
  4 => 
  array (
    0 => '4',
    'id' => '4',
    1 => '0',
    'pid' => '0',
    2 => 'article',
    'model' => 'article',
    3 => '成功案例',
    'name' => '成功案例',
    4 => 'cases',
    'catalog' => 'cases',
    5 => 'cases/page_1.html',
    'link' => 'cases/page_1.html',
    6 => '',
    'target' => '',
    7 => '4',
    'porder' => '4',
    8 => 'news.htm',
    'template' => 'news.htm',
    9 => 'show',
    'display' => 'show',
  ),
  5 => 
  array (
    0 => '5',
    'id' => '5',
    1 => '0',
    'pid' => '0',
    2 => 'other',
    'model' => 'other',
    3 => '产品中心',
    'name' => '产品中心',
    4 => 'product',
    'catalog' => 'product',
    5 => 'product/page_1.html',
    'link' => 'product/page_1.html',
    6 => '',
    'target' => '',
    7 => '5',
    'porder' => '5',
    8 => 'product.htm',
    'template' => 'product.htm',
    9 => 'show',
    'display' => 'show',
  ),
  6 => 
  array (
    0 => '6',
    'id' => '6',
    1 => '0',
    'pid' => '0',
    2 => 'common',
    'model' => 'common',
    3 => '联系我们',
    'name' => '联系我们',
    4 => '',
    'catalog' => '',
    5 => 'contact.html',
    'link' => 'contact.html',
    6 => '',
    'target' => '',
    7 => '6',
    'porder' => '6',
    8 => 'contact.htm',
    'template' => 'contact.htm',
    9 => 'show',
    'display' => 'show',
  ),
); 
      ?>